**Matrizes**

In [1]:
A = [[1, 2, 3], # 2 rows & 3 columns
     [4, 5, 6]]
print("Matriz A = ", A)

Matriz A =  [[1, 2, 3], [4, 5, 6]]


In [2]:
B = [[1, 3], # 3 rows & 2 columns
     [3, 4],
     [5, 6]]
print("Matriz B = ", B)

Matriz B =  [[1, 3], [3, 4], [5, 6]]


In [5]:
len(A)

2

In [7]:
len(A[0])

3

In [8]:
def shape(A):
  num_rows = len(A)
  num_cols = len(A[0]) if A else 0
  return num_rows, num_cols

In [9]:
print(shape([[1, 2, 3], [3, 2, 1]]))

(2, 3)


In [10]:
def get_row(A, i):
  return A[i] # A[i] is the ith row

def get_column(A, j):
  return [A_i[j] #jth element of row A_i
          for A_i in A] # for each row A_i

In [11]:
print(get_row([[1, 2, 3], [3, 2, 1]], 1))

[3, 2, 1]


In [12]:
print(get_column([[1, 2, 3], [3, 2, 1]], 2))

[3, 1]


In [14]:
x = [item for row in A
          for item in row
          if item % 2 == 0]

In [15]:
x

[2, 4, 6]

In [17]:
def make_matrix(num_rows, num_cols, entry_fn):
  """returns a num_rows x num_cols matrix
  whose (i, j) entry in entry_fn(i, j)"""
  return [[entry_fn(i, j) # given i, create a list
          for j in range(num_cols)]
          for i in range(num_rows)] # create one list for each i

Tensores em Python

In [21]:
from numpy import array
T = array([
    [[1,2,3],     [4,5,6],     [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]],
    ])

In [22]:
print(T.shape)
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
