<a href="https://colab.research.google.com/github/thomazgg/Python.ipynb/blob/main/AprendizagemSupervisionada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Hands-on

Classificador de tipo de flor Íris usando o algoritmo KNN da biblioteca SK-Learn

In [1]:
#Import modules
import numpy as np
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [35]:
#Import and load data
iris = datasets.load_iris()

In [36]:
#X = iris.data[:, [0, 1, 2, 3]]
X = iris.data
y = iris.target

In [37]:
# Dividir os dados em conjuntos de dados de treinamento e teste.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
print('There are {} samples in the training set and {} samples in the test set'.
format(len(X_train), len(X_test)))

There are 105 samples in the training set and 45 samples in the test set


In [38]:
X_test

array([[5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 4. , 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.5, 2.8, 4.6, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 3.6, 1.4, 0.1],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3. , 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [6.2, 2.9, 4.3, 1.3],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 3.1, 5.5, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2

In [39]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [40]:
# Instanciar um objeto KNN
knn = KNeighborsClassifier(n_neighbors=7)

In [41]:
# Treinar o modelo
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [42]:
knn.predict_proba([[4.8, 2.8, 2.1, 3.3]])

array([[0.14285714, 0.85714286, 0.        ]])

In [43]:
knn.predict([[4.8, 2.8, 2.1, 3.3]])

array([1])

In [44]:
# validando o modelo com o conjunto de dados de teste
knn.score(X_test, y_test)

0.9777777777777777

In [45]:
del knn

#Atividade
##Criar um classificador para vinhos usando o SK-Learn KNN e o dataset Wine, considerando:

*   Carregue o dataset Wine com o comando: datasets.load_wine()
*   Usar apenas os atributos álcool [0], ácido málico [1], magnésio [4] e flavonóides [6]
*   Dividir a base de dados entre treinamento e teste na relação 70/30
*   Instancie o classificador KNN com 7 vizinhos, anote a acurácia e depois reinstancie o classificador com
4 vizinhos e compare a acurácia.
*   Envie o seu arquivo notebook (.ipynb) no Teams


In [46]:
#Import and load data
wine = datasets.load_wine()

In [47]:
#X = wine.data[:, [0, 1, 4, 6]]
X = wine.data[:, [0, 1, 4, 6]]
y = wine.target

In [48]:
# Dividir os dados em conjuntos de dados de treinamento e teste.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
print('There are {} samples in the training set and {} samples in the test set'.
format(len(X_train), len(X_test)))

There are 124 samples in the training set and 54 samples in the test set


In [49]:
X_test

array([[ 13.74,   1.67, 118.  ,   2.9 ],
       [ 12.79,   2.67, 112.  ,   1.36],
       [ 12.37,   1.13,  87.  ,   3.1 ],
       [ 13.56,   1.73, 116.  ,   2.78],
       [ 13.05,   5.8 ,  86.  ,   2.65],
       [ 11.56,   2.05, 119.  ,   5.08],
       [ 14.06,   2.15, 121.  ,   2.51],
       [ 12.36,   3.83,  88.  ,   0.92],
       [ 12.25,   1.73,  80.  ,   2.03],
       [ 12.08,   1.83,  81.  ,   1.5 ],
       [ 13.36,   2.56,  89.  ,   0.5 ],
       [ 13.88,   5.04,  80.  ,   0.34],
       [ 14.2 ,   1.76, 112.  ,   3.39],
       [ 12.37,   1.07,  88.  ,   3.75],
       [ 13.58,   2.58, 105.  ,   0.84],
       [ 12.  ,   0.92,  86.  ,   2.26],
       [ 13.76,   1.53, 132.  ,   2.74],
       [ 14.19,   1.59, 108.  ,   3.93],
       [ 12.64,   1.36, 100.  ,   1.41],
       [ 13.83,   1.65,  94.  ,   2.99],
       [ 13.11,   1.01,  78.  ,   3.18],
       [ 13.05,   1.65,  98.  ,   2.43],
       [ 13.24,   2.59, 118.  ,   2.69],
       [ 12.51,   1.73,  85.  ,   1.92],
       [ 12.33, 

In [50]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [51]:
# Instanciar um objeto KNN
knn = KNeighborsClassifier(n_neighbors=7)

In [29]:
# Treinar o modelo
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [30]:
knn.predict_proba([[4.8, 2.8, 2.1, 3.3]])

array([[0., 1., 0.]])

In [31]:
knn.predict([[4.8, 2.8, 2.1, 3.3]])

array([1])

In [32]:
# validando o modelo com o conjunto de dados de teste
knn.score(X_test, y_test)

0.6666666666666666

In [52]:
# Instanciar um objeto KNN
knn = KNeighborsClassifier(n_neighbors=4)

In [53]:
# Treinar o modelo
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [54]:
knn.predict_proba([[4.8, 2.8, 2.1, 3.3]])

array([[0., 1., 0.]])

In [55]:
knn.predict([[4.8, 2.8, 2.1, 3.3]])

array([1])

In [56]:
# validando o modelo com o conjunto de dados de teste
knn.score(X_test, y_test)

0.8148148148148148